# Version 20240908, by Eriberto Mota, modified by Christoph Raitzig

name: full-check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install_dependencies
      run: sudo apt install libjpeg-dev libpng-dev libwebp-dev libcurl4-gnutls-dev libncurses5-dev libexif-dev pkg-config
    - name: first_build
      run: |
           ./autogen.sh
           ./configure
           make
           sudo make install
           sudo make uninstall
           make distclean 
    - name: second_build
      run: |
           ./autogen.sh
           ./configure
           make
           sudo make install
    - name: run_program
      run: |
           TERM=xterm-256color jp2a --colors .github/jp2a.jpg
           TERM=xterm-256color jp2a --background=light -b -f -x -y --colors .github/jp2a.jpg
    - name: run_tests
      run: |
          make test

  zig-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: install_dependencies
      run: sudo apt install libjpeg-dev libpng-dev libwebp-dev libcurl4-gnutls-dev libncurses5-dev libexif-dev pkg-config
    - uses: goto-bus-stop/setup-zig@v2
    - name: build with zig
      run: |
          ./autogen.sh
          CC="zig cc" ./configure
          make
    - name: run tests
      run: |
          make test
